/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package graficos;

import Conexiones.dbPersona;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyectohotel.Persona;

/**
 *
 * @author Diego
 */
public class NuevaPersona extends javax.swing.JInternalFrame {

    /**
     * Creates new form NuevaPersona
     */
    public NuevaPersona() {
        initComponents();
        mostrar("");
        inhabilitar();
        
        
    }
    
    //Variable de control
    private String accion="guarda";
    
    void inhabilitar (){
        txtIDpersona.setVisible(false);
        txtNuevaPersonaApellido.setEnabled(false);
        txtNuevaPersonaNombre.setEnabled(false);
        txtNuevaPersonaDNI.setEnabled(false);
        txtNuevaPersonaTelefono.setEnabled(false);
        
        btnNuevoUsuarioAgregar.setEnabled(false);
        btnNuevoUsuarioCancelar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
        txtIDpersona.setText("");
        txtNuevaPersonaApellido.setText("");
        txtNuevaPersonaNombre.setText("");
        txtNuevaPersonaDNI.setText("");
        txtNuevaPersonaTelefono.setText("");
    }
    
    void habilitar(){
        txtIDpersona.setVisible(false);
        
        txtNuevaPersonaApellido.setEnabled(true);
        txtNuevaPersonaNombre.setEnabled(true);
        txtNuevaPersonaDNI.setEnabled(true);
        txtNuevaPersonaTelefono.setEnabled(true);
        
        btnNuevoUsuarioAgregar.setEnabled(true);
        btnNuevoUsuarioCancelar.setEnabled(true);
        btnEliminar.setEnabled(true);
        
        txtIDpersona.setText("");
        txtNuevaPersonaApellido.setText("");
        txtNuevaPersonaNombre.setText("");
        txtNuevaPersonaDNI.setText("");
        txtNuevaPersonaTelefono.setText("");
    }
    
    //Ocultar_Columna me oculta la columna de ID de Persona
    void ocultar_columna(){
        tableNuevaPersona.getColumnModel().getColumn(0).setMaxWidth(0);
        tableNuevaPersona.getColumnModel().getColumn(0).setMinWidth(0);
        tableNuevaPersona.getColumnModel().getColumn(0).setPreferredWidth(0);
        
    }
    
    //Funcion para llenar la tabla con persona
    void mostrar (String buscar){
        try {
            DefaultTableModel modelo;
            dbPersona func = new dbPersona();
            modelo = func.mostrar(buscar);
            
            tableNuevaPersona.setModel(modelo);
            ocultar_columna();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnNuevoUsuarioAgregar = new javax.swing.JButton();
        btnNuevoUsuarioCancelar = new javax.swing.JButton();
        btnNuevoUsuarioGuardar = new javax.swing.JButton();
        txtNuevaPersonaNombre = new javax.swing.JTextField();
        txtNuevaPersonaApellido = new javax.swing.JTextField();
        txtNuevaPersonaDNI = new javax.swing.JTextField();
        txtNuevaPersonaTelefono = new javax.swing.JTextField();
        txtIDpersona = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableNuevaPersona = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtBuscar = new javax.swing.JTextPane();
        btnBuscar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setTitle("Nueva Persona");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de Cliente"));

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellido:");

        jLabel3.setText("DNI:");

        jLabel4.setText("Telefono:");

        btnNuevoUsuarioAgregar.setText("Agregar");
        btnNuevoUsuarioAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioAgregarActionPerformed(evt);
            }
        });

        btnNuevoUsuarioCancelar.setText("Cancelar");
        btnNuevoUsuarioCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioCancelarActionPerformed(evt);
            }
        });

        btnNuevoUsuarioGuardar.setText("Nuevo");
        btnNuevoUsuarioGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioGuardarActionPerformed(evt);
            }
        });

        txtNuevaPersonaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaPersonaNombreActionPerformed(evt);
            }
        });

        txtNuevaPersonaApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaPersonaApellidoActionPerformed(evt);
            }
        });

        txtNuevaPersonaDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaPersonaDNIActionPerformed(evt);
            }
        });

        txtNuevaPersonaTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNuevaPersonaTelefonoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevoUsuarioGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevoUsuarioAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNuevoUsuarioCancelar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNuevaPersonaNombre)
                            .addComponent(txtNuevaPersonaApellido)
                            .addComponent(txtNuevaPersonaTelefono)
                            .addComponent(txtIDpersona)
                            .addComponent(txtNuevaPersonaDNI))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtNuevaPersonaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNuevaPersonaApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNuevaPersonaDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNuevaPersonaTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtIDpersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoUsuarioCancelar)
                    .addComponent(btnNuevoUsuarioAgregar)
                    .addComponent(btnNuevoUsuarioGuardar))
                .addGap(30, 30, 30))
        );

        btnNuevoUsuarioCancelar.getAccessibleContext().setAccessibleName("");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Listado de Clientes"));

        tableNuevaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableNuevaPersona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNuevaPersonaMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableNuevaPersona);

        jLabel6.setText("Buscar:");

        jScrollPane6.setViewportView(txtBuscar);

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBuscar)
                        .addComponent(btnActualizar)
                        .addComponent(btnEliminar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(btnSalir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoUsuarioCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioCancelarActionPerformed
        inhabilitar();
    }//GEN-LAST:event_btnNuevoUsuarioCancelarActionPerformed

    //Funcion para crear un nuevo Cliente o Editarlo
    
    private void btnNuevoUsuarioAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioAgregarActionPerformed
        if(txtNuevaPersonaNombre.getText().equals("") && txtNuevaPersonaApellido.getText().equals("") && txtNuevaPersonaDNI.getText().equals("") && txtNuevaPersonaTelefono.getText().equals("") ){
        JOptionPane.showMessageDialog(null, "Se deben llenar todos los campos");
        }else{
        Persona nuePersona = new Persona();
        nuePersona.setApellido(txtNuevaPersonaApellido.getText());
        nuePersona.setNombre(txtNuevaPersonaNombre.getText());
        nuePersona.setDNI(Integer.parseInt(txtNuevaPersonaDNI.getText()));
        nuePersona.setTelefono(Integer.parseInt(txtNuevaPersonaTelefono.getText()));
        
        dbPersona Nuevo = new dbPersona();
        
        if (accion.equals("guardar")){
            if(Nuevo.insertar(nuePersona)){
                JOptionPane.showMessageDialog(null, "El cliente se agrego correctamente");
                mostrar("");
                inhabilitar();
            }
        }else if(accion.equals("editar")){
            nuePersona.setIdPersona(Integer.parseInt(txtIDpersona.getText()));
            if(Nuevo.editar(nuePersona)){
                JOptionPane.showMessageDialog(null, "El cliente se edito correctamente");
                mostrar("");
                inhabilitar();
            }
        }
        }
        
    }//GEN-LAST:event_btnNuevoUsuarioAgregarActionPerformed

    //Habilito las casillas para crear un nuevo Cliente
    
    private void btnNuevoUsuarioGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioGuardarActionPerformed
        habilitar();
        btnNuevoUsuarioAgregar.setText("Guardar");
        accion="guardar";
    }//GEN-LAST:event_btnNuevoUsuarioGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
            mostrar("");
            inhabilitar();
    }//GEN-LAST:event_btnActualizarActionPerformed

    //Eliminar un Cliente
    
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(!txtIDpersona.getText().equals("")){
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que debea eliminar al cliente?","Confirmar",2);
            
            if(confirmacion == 0){
                Persona dts = new Persona();
                dbPersona func = new dbPersona();
                
                dts.setIdPersona(Integer.parseInt(txtIDpersona.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrar(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    //Funcion para transladar los datos de la tabla al pane de cliente para editar
    
    private void tableNuevaPersonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNuevaPersonaMouseClicked
        btnNuevoUsuarioAgregar.setText("Editar");
        habilitar();
        btnEliminar.setEnabled(true);
        accion="editar";
        
        int fila = tableNuevaPersona.rowAtPoint(evt.getPoint());
        
        txtIDpersona.setText(tableNuevaPersona.getValueAt(fila, 0).toString());
        txtNuevaPersonaApellido.setText(tableNuevaPersona.getValueAt(fila,1).toString());
        txtNuevaPersonaNombre.setText(tableNuevaPersona.getValueAt(fila,2).toString());
        txtNuevaPersonaDNI.setText(tableNuevaPersona.getValueAt(fila,3).toString());
        txtNuevaPersonaTelefono.setText(tableNuevaPersona.getValueAt(fila,4).toString());  
    }//GEN-LAST:event_tableNuevaPersonaMouseClicked

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    //Funciones para apretar ENTER y pasar el curso al siguiente TBox
    
    private void txtNuevaPersonaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaPersonaNombreActionPerformed
        txtNuevaPersonaNombre.transferFocus();
    }//GEN-LAST:event_txtNuevaPersonaNombreActionPerformed

    private void txtNuevaPersonaApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaPersonaApellidoActionPerformed
        txtNuevaPersonaApellido.transferFocus();
    }//GEN-LAST:event_txtNuevaPersonaApellidoActionPerformed

    private void txtNuevaPersonaDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaPersonaDNIActionPerformed
        txtNuevaPersonaDNI.transferFocus();
    }//GEN-LAST:event_txtNuevaPersonaDNIActionPerformed

    private void txtNuevaPersonaTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNuevaPersonaTelefonoActionPerformed
        txtNuevaPersonaTelefono.transferFocus();
    }//GEN-LAST:event_txtNuevaPersonaTelefonoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoUsuarioAgregar;
    private javax.swing.JButton btnNuevoUsuarioCancelar;
    private javax.swing.JButton btnNuevoUsuarioGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableNuevaPersona;
    private javax.swing.JTextPane txtBuscar;
    private javax.swing.JTextField txtIDpersona;
    private javax.swing.JTextField txtNuevaPersonaApellido;
    private javax.swing.JTextField txtNuevaPersonaDNI;
    private javax.swing.JTextField txtNuevaPersonaNombre;
    private javax.swing.JTextField txtNuevaPersonaTelefono;
    // End of variables declaration//GEN-END:variables
}
